### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by tebriel** [tpuronen/cppspec#4]
Wanted to read more about the framework but website is down. Didn't know how else to contact. Thanks!

**Comment by dannystaple** [comment]
The domain seems to have expired there. Has cppspec gone extinct?

**Comment by rdammkoehler** [comment]
seems like it

**Comment by tpuronen** [comment]
Hi, the old server is not running anymore. I copied some of the introduction to Github. I'll try to add some more documentation there as well. Thanks for noticing this!
