### ISSUE TITLE
Can't compile cppspec on centos5-64 machine

### ISSUE THREAD

**Issue by chidouglass** [tpuronen/cppspec#5]
I've obtained the latest sources and cmake is able to find boost (version 1.49) when run. 

But on running make, I get these errors pasted below (sorry for the massive paste).

Any idea why this is happening?

Thanks

${CPPSPEC_DIRECTORY}/cppspec/test/../include/Timer.h:27: error: ISO C++ forbids declaration of 'shared_ptr' with no type
${CPPSPEC_DIRECTORY}/cppspec/test/../include/Timer.h:27: error: invalid use of '::'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/Timer.h:27: error: expected ';' before '<' token
${CPPSPEC_DIRECTORY}/cppspec/test/../include/BoostTimer.h:39: error: 'boost::chrono' has not been declared
${CPPSPEC_DIRECTORY}/cppspec/test/../include/BoostTimer.h:39: error: ISO C++ forbids declaration of 'time_point' with no type
${CPPSPEC_DIRECTORY}/cppspec/test/../include/BoostTimer.h:39: error: expected ';' before 'startTime'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:60: error: 'mutex' in namespace 'boost' does not name a type
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:61: error: 'condition_variable' in namespace 'boost' does not name a type
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:65: error: 'mutex' in namespace 'boost' does not name a type
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:67: error: 'mutex' in namespace 'boost' does not name a type
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:104: error: 'thread' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:104: error: 'thread' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:104: error: template argument 1 is invalid
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:104: error: template argument 2 is invalid
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h: In member function 'CppSpec::Runnable\* CppSpec::ThreadPool::Consumer::getSpec()':
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:17: error: 'lock_guard' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:17: error: 'mutex' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:17: error: 'specsLock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:17: error: 'lock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h: In member function 'void CppSpec::ThreadPool::Consumer::addResult(const CppSpec::SpecResult&)':
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:27: error: 'lock_guard' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:27: error: 'mutex' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:27: error: 'resultLock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:27: error: 'lock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:29: error: 'cond' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h: In member function 'void CppSpec::ThreadPool::Consumer::incrementThreadCount()':
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:49: error: 'lock_guard' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:49: error: 'mutex' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:49: error: 'threadCountLock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:49: error: 'lock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h: In member function 'void CppSpec::ThreadPool::Consumer::decrementThreadCount()':
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:54: error: 'lock_guard' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:54: error: 'mutex' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:54: error: 'threadCountLock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:54: error: 'lock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h: In member function 'void CppSpec::ThreadPool::start(InputIterator, InputIterator, CppSpec::Reporter&)':
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:81: error: request for member 'push_back' in '((CppSpec::ThreadPool_)this)->CppSpec::ThreadPool::threads', which is of non-class type 'int'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:81: error: expected type-specifier
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:81: error: expected `)'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:85: error: 'unique_lock' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:85: error: 'mutex' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:85: error: 'class CppSpec::ThreadPool::Consumer' has no member named 'resultLock'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:85: error: there are no arguments to 'lock' that depend on a template parameter, so a declaration of 'lock' must be available
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:85: error: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:87: error: 'class CppSpec::ThreadPool::Consumer' has no member named 'cond'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:87: error: 'lock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:91: error: 'lock' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:97: error: 'thread' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:97: error: 'thread' is not a member of 'boost'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:97: error: template argument 1 is invalid
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:97: error: template argument 2 is invalid
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:97: error: expected initializer before 'it'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:97: error: 'it' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:97: error: request for member 'end' in '((CppSpec::ThreadPool_)this)->CppSpec::ThreadPool::threads', which is of non-class type 'int'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp: In constructor 'CppSpec::SpecRunner::SpecRunner(int, const char**)':
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:42: error: 'options_description' is not a member of 'boost::program_options'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:42: error: expected `;' before 'options'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:43: error: 'options' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:44: error: 'value' is not a member of 'boost::program_options'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:44: error: expected primary-expression before '>' token
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:44: error: expected primary-expression before ')' token
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:46: error: 'value' is not a member of 'boost::program_options'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:46: error: expected primary-expression before '>' token
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:46: error: expected primary-expression before ')' token
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:47: error: 'value' is not a member of 'boost::program_options'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:47: error: expected primary-expression before '>' token
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:50: error: invalid use of undefined type 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/SpecRunner.h:10: error: forward declaration of 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:51: error: 'store' is not a member of 'boost::program_options'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:51: error: 'parse_command_line' is not a member of 'boost::program_options'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:52: error: 'notify' is not a member of 'boost::program_options'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:53: error: invalid use of undefined type 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/SpecRunner.h:10: error: forward declaration of 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp: In destructor 'virtual CppSpec::SpecRunner::~SpecRunner()':
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:60: warning: possible problem detected in invocation of delete operator:
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:60: warning: invalid use of undefined type 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/SpecRunner.h:10: warning: forward declaration of 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:60: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined.
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp: In member function 'CppSpec::Reporter\* CppSpec::SpecRunner::createReporter(CppSpec::OutputStream&)':
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:72: error: invalid use of undefined type 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/SpecRunner.h:10: error: forward declaration of 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:73: error: no match for 'operator[]' in '_((CppSpec::SpecRunner_)this)->CppSpec::SpecRunner::arguments["output"]'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:73: error: expected primary-expression before '>' token
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:73: error: expected primary-expression before ')' token
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:75: error: invalid use of undefined type 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/SpecRunner.h:10: error: forward declaration of 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:79: error: invalid use of undefined type 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/SpecRunner.h:10: error: forward declaration of 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:80: error: no match for 'operator[]' in '_((CppSpec::SpecRunner_)this)->CppSpec::SpecRunner::arguments["report-dir"]'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:80: error: expected primary-expression before '>' token
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:80: error: expected primary-expression before ')' token
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp: In member function 'bool CppSpec::SpecRunner::runSpecs(const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:99: error: invalid use of undefined type 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/test/../include/SpecRunner.h:10: error: forward declaration of 'struct boost::program_options::variables_map'
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:100: error: 'boost::thread' has not been declared
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h: In member function 'void CppSpec::ThreadPool::start(InputIterator, InputIterator, CppSpec::Reporter&) [with InputIterator = __gnu_cxx::__normal_iterator<CppSpec::Runnable**, std::vector<CppSpec::Runnable*, std::allocator<CppSpec::Runnable*> > >]':
${CPPSPEC_DIRECTORY}/cppspec/src/SpecRunner.cpp:103:   instantiated from here
${CPPSPEC_DIRECTORY}/cppspec/test/../include/ThreadPool.h:85: error: 'lock' was not declared in this scope
In file included from ${CPPSPEC_DIRECTORY}/cppspec/test/../include/BoostTimer.h:20,
                 from ${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp:17:
${CPPSPEC_DIRECTORY}/cppspec/test/../include/Timer.h:21:32: error: boost/shared_ptr.hpp: No such file or directory
In file included from ${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp:17:
${CPPSPEC_DIRECTORY}/cppspec/test/../include/BoostTimer.h:21:28: error: boost/chrono.hpp: No such file or directory
make[2]: **\* [test/CMakeFiles/CppSpecGTest.dir/__/src/SpecRunner.cpp.o] Error 1
${CPPSPEC_DIRECTORY}/cppspec/test/../include/Timer.h:27: error: 'boost' has not been declared
${CPPSPEC_DIRECTORY}/cppspec/test/../include/Timer.h:27: error: ISO C++ forbids declaration of 'shared_ptr' with no type
${CPPSPEC_DIRECTORY}/cppspec/test/../include/Timer.h:27: error: expected ';' before '<' token
${CPPSPEC_DIRECTORY}/cppspec/test/../include/BoostTimer.h:39: error: 'boost' has not been declared
${CPPSPEC_DIRECTORY}/cppspec/test/../include/BoostTimer.h:39: error: ISO C++ forbids declaration of 'time_point' with no type
${CPPSPEC_DIRECTORY}/cppspec/test/../include/BoostTimer.h:39: error: expected ';' before 'startTime'
${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp: In member function 'virtual void CppSpec::BoostTimer::start()':
${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp:29: error: 'startTime' was not declared in this scope
${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp:29: error: 'boost' has not been declared
${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp: In member function 'virtual std::string CppSpec::BoostTimer::stop()':
${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp:33: error: 'boost' has not been declared
${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp:33: error: expected primary-expression before 'double'
${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp:33: error: expected `;' before 'double'
${CPPSPEC_DIRECTORY}/cppspec/src/BoostTimer.cpp:35: error: 'secs' was not declared in this scope

**Comment by tpuronen** [comment]
Looks like Boost includes are not used during compile. Can you check if BOOST_INCLUDE_DIRS is really set in makefiles after running CMake.

**Comment by chidouglass** [comment]
It is set - I realise that I had to change "BOOST_INCLUDE_DIRS" to "Boost_INCLUDE_DIRS" in the test CMakeLists.txt file in order to get rid of that issue. I don't know why this was an issue for me, I assume it hasn't been an issue for anyone else.

Anyway thanks for the help and the quick reply. :)

**Comment by tpuronen** [comment]
Good to hear you got it solved.

Looks like Boost_INCLUDE_DIRS is the correct form, please send a pull request of your change!
